language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install gfortran

install:
  - pip install -r requirements.txt
  - pip install .

before_script:
  - ls /home/travis/build/knaidoo29/mistree/mistree/levy_flight
  - ls /home/travis/build/knaidoo29/mistree/mistree/mst
  - ls /home/travis/build/knaidoo29/mistree/mistree/coordinates

script: python setup.py test

after_success:
  - coveralls
