language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install gfortran

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script: python setup.py test

after_success:
  - coverage run --source=mistree setup.py test
  - codecov
